### ISSUE TITLE
API Key required to be plaintext in serverless.yml

### ISSUE THREAD

**Issue by ethanwe** [newrelic/serverless-newrelic-lambda-layers#117]
We were switching our config to use the lambda extension and through testing realized that the user API key is required. Since we have a policy to keep secrets outside of source control, we can't use the plaintext API key in the serverless.yml. Is there a way to provide this API key to the plugin in a better way?

Until we have a way to provide an API key through secrets manager or some other secure method, we'll keep using CloudWatch log subscriptions.

Only issue so far with this plugin! I definitely appreciate how easy it is to set up.

**Comment by mrickard** [comment]
Thank you for the report, @ethanwe ! According to the serverless spec, you should be able to evaluate environment variables or command-line options at runtime. See https://www.serverless.com/framework/docs/providers/aws/guide/variables/

Would that kind of solution work for you?

**Comment by ethanwe** [comment]
That did it. Thanks for your help! I didn't realize serverless framework handled for us.

For those that find this issue, I was able to store the secret called "newRelicTest" in secrets manager with the API key as a property called "NEW_RELIC_USER_KEY". After that, you reference it in the serverless.yml like this:
```
custom:
  newRelicUserKey: ${ssm:/aws/reference/secretsmanager/newRelicTest~true}
  newRelic:
    apiKey: ${self:custom.newRelicUserKey.NEW_RELIC_USER_KEY}
```
