### ISSUE TITLE
Shouldn't rely on hard coded integration names

### ISSUE THREAD

**Issue by keegoid-nr** [newrelic/serverless-newrelic-lambda-layers#160]
### Current Behavior:

This issue occurs when a Metric Streams type of integration already exists with a custom name. For example:

```yaml
custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    logLevel: debug
```

It couldn't find the existing MS integration. It also created a log subscription filter even though the Extension is being used.

```log
$ npx sls deploy
Serverless: Plugins: ["serverless-newrelic-lambda-layers"]
Serverless: Adding NewRelic layer to layer-nodejs14x
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: No New Relic AWS Lambda integration found for this New Relic linked account and aws account.
Serverless: Please enable the configuration manually or add the 'enableIntegration' config var to your serverless.yaml file.
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service kmullaney-ms-test2.zip file to S3 (70.49 kB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....................
Serverless: Stack update finished...
Service Information
service: kmullaney-ms-test2
stage: prod
region: us-west-2
stack: kmullaney-ms-test2-prod
resources: 8
api keys:
  None
endpoints:
functions:
  layer-nodejs14x: kmullaney-ms-test2-prod-layer-nodejs14x
layers:
  None
Serverless: log filter: ?"REPORT" ?"NR_LAMBDA_MONITORING" ?"Task timed out" ?"RequestId"
Serverless: Configuring New Relic log subscription for layer-nodejs14x
Serverless: Adding New Relic log subscription to kmullaney-ms-test2-prod-layer-nodejs14x
```

Providing the `linkedAccount`:

```yaml
custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    logLevel: debug
    linkedAccount: gts-newrelic
```

It finds my MS integration. It apparently doesn't care what type of integration it is.

```log
Serverless: Existing New Relic integration found for this linked account and aws account, skipping creation.
```

Commenting out the `linkedAccount` and adding `enableIntegration`, it creates an API polling integration despite the MS integration existing for the same AWS account. So this poses is problem for those who use the Serverless plugin, which causes duplicate integration issues.

```yaml
custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    logLevel: debug
    enableIntegration: true
    # linkedAccount: gts-newrelic
```

```log
Serverless: No New Relic AWS Lambda integration found for this New Relic linked account and aws account.
Serverless: Enabling New Relic integration for linked account: New Relic Lambda Integration - 1234567 and aws account: 123456789876.
```

### Expected Behavior:

For those with an existing MS integration:

1. The Serverless Plugin should be able to find the account given only the AWS account and New Relic account Ids. There should not be any need to specify the `linkedAccount` or `enableIntegration`.
2. A subscription filter should not be created if the Extension is being used and `disableAutoSubscription: true` should be the default in that case.

The following should be sufficient to find the MS integration with a custom name.

```yaml
custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
```

```log
Serverless: Existing New Relic integration found for this linked account and aws account, skipping creation.
Serverless: Skipping adding log subscription because Extension is enabled.
```

**Comment by mrickard** [comment]
@keegoid-nr Thank you! This should be addressed in the v2.2.1 release (released this morning), which queries NerdGraph and avoids creating an integration if there are any current integrations. I won't close this just yet, though, to ensure that disableAutoSubscription is being honored.

**Comment by keegoid-nr** [comment]
`disableAutoSubscription` does not appear to be honored when the Extension is in use. Testing with [2.2.1](https://github.com/newrelic/serverless-newrelic-lambda-layers/tree/v2.2.1) it still creates the subscription filter.

### Config

```
custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    logLevel: debug
```

### Output

```
[serverless-plugin]kmullaney/working[0|0]$ npx sls deploy
Serverless: Plugins: ["serverless-newrelic-lambda-layers"]
Serverless: Adding NewRelic layer to nodejs14x
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Existing New Relic integration found for this linked account and aws account, skipping creation.
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service kmullaney-ms-test3.zip file to S3 (70.6 kB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....................
Serverless: Stack update finished...
Service Information
service: kmullaney-ms-test3
stage: prod
region: us-west-2
stack: kmullaney-ms-test3-prod
resources: 8
api keys:
  None
endpoints:
functions:
  nodejs14x: kmullaney-ms-test3-prod-nodejs14x
layers:
  None
Serverless: log filter: ?"REPORT" ?"NR_LAMBDA_MONITORING" ?"Task timed out" ?"RequestId"
Serverless: Configuring New Relic log subscription for nodejs14x
Serverless: Adding New Relic log subscription to kmullaney-ms-test3-prod-nodejs14x
Toggle on monitoring with the Serverless Dashboard: run "serverless"
```
