### ISSUE TITLE
Failure to retrieve LicenseKey results in "Unsupported runtime" warning

### ISSUE THREAD

**Issue by tomasbareikis-home24** [newrelic/serverless-newrelic-lambda-layers#179]
I have `config.enableExtension` set to `true` (which is the default value).

If for some reason, the fetching of license key [here](https://github.com/newrelic/serverless-newrelic-lambda-layers/blob/master/src/index.ts#L169) fails, the `config.enableExtension` value is silently switched to `false`.

Later in the process, the `enableExtension` configuration value is checked [here](https://github.com/newrelic/serverless-newrelic-lambda-layers/blob/master/src/index.ts#L399). If the runtime is supported, but `enableExtension` is `false`, warning `Unsupported runtime <runtime name here> for NewRelic layer; skipping` is shown. This not a correct warning message for this situation.

Serverless version:

```
Framework Core: 2.70.0 (local)
Plugin: 5.5.2
SDK: 4.3.0
Components: 3.18.1
```

Plugin version: `v2.2.1`

This is a snippet of `serverless.yml` to reproduce the issue:
```
custom:
  newRelic:
    accountId: xxxxxxx
    apiKey: foo
    nrRegion: eu
    logEnabled: true
    enableExtension: true
    enableFunctionLogs: true
    logLevel: debug
```

I intentionally provide wrong `apiKey` for fetching of license key to fail.

The runtime is `provided.al2`, which is a supported runtime:
```
provider:
  name: aws
  runtime: provided.al2
```

`serverless deploy` or `serverless package` shows a misleading warning:

```
Unsupported runtime "provided.al2" for NewRelic layer; skipping.
```

The deployment still continues and succeeds, but the lambda function is then missing the New Relic integration layer.

I would expect to see a message indicating, that fetching License Key has failed.
