### ISSUE TITLE
Max allowed size of 272629760

### ISSUE THREAD

**Issue by mits87** [newrelic/serverless-newrelic-lambda-layers#205]
Hi there!

I'm trying to use that plugin with my serverless app but I'm getting this error:
```
UPDATE_FAILED: ConsumerDashexportDashtransactionsLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "Code uncompressed size is greater than max allowed size of 272629760. (Service: Lambda, Status Code: 400, Request ID: e092baa2-a90e-4033-995d-0ae8fd6881ef, Extended Request ID: null)" (RequestToken: da6662f5-fd72-e7c9-7b32-7ce6a872097c, HandlerErrorCode: InvalidRequest)
```

my serverless.yml:
```
service: api

frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-log-retention
  - serverless-newrelic-lambda-layers
  - serverless-offline
  - serverless-domain-manager
  - serverless-stage-manager
  - serverless-jetpack

package:
  excludeDevDependencies: true
  individually: true

custom:
  typeScript:
    tsconfigFilePath: ./tsconfig.build.json
  newRelic:
    accountId: XXXXX
    apiKey: XXXXX
    nrRegion: 'eu'
    enableExtension: true
    enableIntegration: true
    enableFunctionLogs: true
    logEnabled: true
    cloudWatchFilter: '*'
    linkedAccount: dev

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 1
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1,
    NODE_ENV: ${self:provider.stage}

functions:
  api:
    handler: src/events/api.handler
    events:
      - http:
          path: /{any+}
          method: ANY
          cors: true
```

Any ideas how to solve it?
