### ISSUE TITLE
TypeError: Cannot read property ‘secretExists’ of undefined 

### ISSUE THREAD

**Issue by harrythedev** [newrelic/serverless-newrelic-lambda-layers#219]
We’re using User API key generated by NR user account.
this is how our serverless.yml is configured.

```
custom:
  newRelic:
    accountId: ${self:custom.config.environment.NEW_RELIC_ACCOUNT_ID}
    apiKey: ${self:custom.config.environment.NEW_RELIC_USER_KEY}
    enableExtension: true
    enableIntegration: true
    logEnabled: true

  provider:
    environment:
      NEW_RELIC_ACCOUNT_ID: ${self:custom.config.environment.NEW_RELIC_ACCOUNT_ID}
      NEW_RELIC_USER_KEY: ${self:custom.config.environment.NEW_RELIC_USER_KEY}
  plugins:
    - serverless-newrelic-lambda-layers
```
and this is config.prod.yml

```
  NEW_RELIC_ACCOUNT_ID: <our production user key>
  NEW_RELIC_USER_KEY: ${ssm:/NEW_RELIC_USER_KEY~true}
```

Build is failing on production with following error:
```
  TypeError: Cannot read property 'secretExists' of undefined



      at NewRelicLambdaLayerPlugin.<anonymous> (/codebuild/output/src058836924/src/node_modules/serverless-newrelic-lambda-layers/dist/index.js:142:34)



      at Generator.next (<anonymous>)



      at fulfilled (/codebuild/output/src058836924/src/node_modules/serverless-newrelic-lambda-layers/dist/index.js:5:58)



      at runNextTicks (internal/process/task_queues.js:59:5)



      at processImmediate (internal/timers.js:412:9)



      at process.topLevelDomainCallback (domain.js:130:23)



 



     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

```
