### ISSUE TITLE
Where are log prefixes being set?

### ISSUE THREAD

**Issue by JordanPawlett** [newrelic/serverless-newrelic-lambda-layers#241]
Sorry if this is a stupid question, or not relevant to the library!

We're using this plugin to integrate our serverless stack with newrelic. Logs and lambda instrumentation are working fine. 
However, our logs have are appearing in newrelic & cloudwatch with quite a verbose Prefix which is unnecessary _as we add our own log 'type' and timestamp_ we'd like to remove.

`2022-04-29T16:22:55.366Z d919413f-b334-4abb-ace7-f964d9249085 DEBUG [2022-04-29T16:22:55.308Z] DEBUG this is a log message`

``2022-04-29T16:22:55.366Z d919413f-b334-4abb-ace7-f964d9249085 DEBUG`` being the prefix in question...

Our plugin configuration looks like this.
```
    newRelic:
      accountId: ${self:custom.newRelicKeys.accountId}
      apiKey: ${self:custom.newRelicKeys.apiKey}
      enableFunctionLogs: true
      enableExtension: true
      enableIntegration: true
```

Apologise if this prefix is configured somewhere outside of the extension.
