### ISSUE TITLE
Add ability to pass labels

### ISSUE THREAD

**Issue by briangweber** [newrelic/serverless-newrelic-lambda-layers#349]
We would like to set some labels on our function, but this does not appear to be possible today. I even tried setting the NEW_RELIC_LABELS environment variable and they do not get picked up. 

Having this in the plugin configuration would be handy. Perhaps:
```
newRelic:
    accountId: 1234
    apiKey: ABCDEFG
    enableExtension: true
    enableExtensionLogs: false
    enableIntegration: true
    enableFunctionLogs: true
    logLevel: warn
    labels: team:myteam;service:myservice
```
