### ISSUE TITLE
Python layer version 41: Failed to import module [HANDLER]

### ISSUE THREAD

**Issue by osama-aref** [newrelic/serverless-newrelic-lambda-layers#366]
Hi,

I've been using `serverless-newrelic-lambda-layers` for a while in my AWS serverless lambda application. Previous versions of the Python layer were working fine, but with the current layer version (_arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicPython39:41_) I'm getting this error: `Runtime.ImportModuleError: Unable to import module 'newrelic_lambda_wrapper': Failed to import module 'src/api/credits/get': No module named 'src/api/credits/get' Traceback`.
No code changes have been made, only change is that the latest layer is getting fetched.
Snippets from serverless.yml:
```
provider:
  name: aws
  runtime: python3.9
  timeout: 10
  memorySize: 128

package:
  # Exclude all files by default, then specify which files to include in each function.
  patterns:
    - '!./**'
  individually: true

custom:
  newRelic:
    accountId: [ACCOUNT ID]
    apiKey: [KEY]
    enableFunctionLogs: true
    nrRegion: 'eu'
    disableLicenseKeySecret: true

functions:
  getCreditsAPI:
    handler: src/api/credits/get.default
    events:
     - http:
         method: GET
         path: /credits
    package:
      patterns:
        - src/api/credits/get.py
```

Any help is appreciated.
Thanks!
