### ISSUE TITLE
Lambda Functions appearing as not instrumented

### ISSUE THREAD

**Issue by juarezjaramillo** [newrelic/serverless-newrelic-lambda-layers#369]
I've instrumented my AWS lambda functions using this plugin. Here are the config details:

 ```
newRelic:
    accountId: <some value>
    apiKey: <some value>
    linkedAccount: <some value>
    enableIntegration: false
    enableFunctionLogs: true
    logLevel: info
    prepend: true        #also tried with false
    stages:
      - production
```

However, on New Relic UI I always see a message when I'm on the summary view of a Lambda function that says:
`If you want to see errors, distributed tracing, and invocations for this function, start instrumenting your Lambda functions.`

The logs appear fine in the UI, and the summary page shows fine as well (duration, # of invocations, etc.). But the Distributed Tracing and Errors views always appear empty.

I've verified on AWS Console that these env vars have been set for the Lambda functions:

```
NEW_RELIC_USE_ESM: true     # for all lambdas (since they have .mjs extension)
NEW_RELIC_ACCOUNT_ID: <some value>
NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED: true
NEW_RELIC_APP_NAME:  <some value>
NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true
NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: true
NEW_RELIC_LAMBDA_HANDLER: <some value>
NEW_RELIC_NO_CONFIG_FILE: true
NEW_RELIC_TRUSTED_ACCOUNT_KEY:  <some value, same as account id>
```

I've also verified the troubleshooting outlined [here](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/troubleshooting/troubleshoot-enabling-serverless-monitoring-aws-lambda/), and still, it doesn't work.

What could be the reason that there's no data in the distributed tracing and error views of all of the lambda functions?
