### ISSUE TITLE
Add ability to include/exclude layer for specific stages

### ISSUE THREAD

**Issue by karopolopoulos** [newrelic/serverless-newrelic-lambda-layers#55]
A big part of serverless is the ability to be able to deploy your same application stack multiple times across multiple accounts by specifying different stages.

It would be great if it was possible to only enable newrelic for some of these stages. E.g.

```
custom:
  newrelic:
    stages:
      - prod    # where provider.stage = prod
````
