### ISSUE TITLE
APM not working with typescript, lambda, serverless 

### ISSUE THREAD

**Issue by svarughese91** [newrelic/serverless-newrelic-lambda-layers#73]
### Application Performance Monitoring Question Template

I am using typescript and serverless to deploy to lambda, i followed this article: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-serverless-monitoring-aws-lambda#connect-aws

I am using node v12 as well
serverless version: v2.1.1

When i deploy I get this error:

    ERROR	Error: Cannot find module './newrelic-lambda-wrapper.js'
    Require stack:
    - /var/task/s_api.js
    - /var/runtime/UserFunction.js
    - /var/runtime/index.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
        at Module._require.o.require (/var/task/serverless_sdk/index.js:9:72934)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/var/task/s_api.js:25:23)
        at Module._compile (internal/modules/cjs/loader.js:1138:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
        at Module.load (internal/modules/cjs/loader.js:986:32)
        at Function.Module._load (internal/modules/cjs/loader.js:879:14)
        at Module.require (internal/modules/cjs/loader.js:1026:19)
        at require (internal/modules/cjs/helpers.js:72:18) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/var/task/s_api.js',
        '/var/runtime/UserFunction.js',
        '/var/runtime/index.js'
      ]
    }

I also tried to add it manually with the node module and adding the config file.  When it runs i keep getting this:

		    2020-09-14T23:36:05.877-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:03.415Z",
    		    "msg": "Cross application tracing is explicitly disabled in serverless_mode."
    		}

    		{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.43.125","pid":8,"time":"2020-09-15T03:36:03.415Z","msg":"Cross application tracing is explicitly disabled in serverless_mode."}

    		2020-09-14T23:36:05.877-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:03.416Z",
    		    "msg": "Logging is disabled by default when serverless_mode is enabled. If desired, enable logging via config file or environment variable and set filepath to a valid path for current environment, stdout or stderr."
    		}

    		{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.43.125","pid":8,"time":"2020-09-15T03:36:03.416Z","msg":"Logging is disabled by default when serverless_mode is enabled. If desired, enable logging via config file or environment variable and set filepath to a valid path for current environment, stdout or stderr."}

    		2020-09-14T23:36:05.877-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:03.416Z",
    		    "msg": "The native-metrics module is disabled by default when serverless_mode is enabled.  If desired, enable the native-metrics module via config file or environment variable."
    		}

    		{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.43.125","pid":8,"time":"2020-09-15T03:36:03.416Z","msg":"The native-metrics module is disabled by default when serverless_mode is enabled. If desired, enable the native-metrics module via config file or environment variable."}

    		2020-09-14T23:36:05.878-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:05.746Z",
    		    "msg": "Cross application tracing is explicitly disabled in serverless_mode."
    		}

    		{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.43.125","pid":8,"time":"2020-09-15T03:36:05.746Z","msg":"Cross application tracing is explicitly disabled in serverless_mode."}

    		2020-09-14T23:36:05.878-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:05.746Z",
    		    "msg": "Logging is disabled by default when serverless_mode is enabled. If desired, enable logging via config file or environment variable and set filepath to a valid path for current environment, stdout or stderr."
    		}

    		{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.43.125","pid":8,"time":"2020-09-15T03:36:05.746Z","msg":"Logging is disabled by default when serverless_mode is enabled. If desired, enable logging via config file or environment variable and set filepath to a valid path for current environment, stdout or stderr."}

    		2020-09-14T23:36:05.878-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:05.746Z",
    		    "msg": "The native-metrics module is disabled by default when serverless_mode is enabled.  If desired, enable the native-metrics module via config file or environment variable."
    		}

Any ideas on whats going on?

**Comment by mrickard** [comment]
Sorry you're having trouble, @svarughese91. Thanks for the report.

With the manual method, do you have the `NEW_RELIC_SERVERLESS_MODE_ENABLED` environment variable set on your lambda function? If so, try removing that environment variable entirely.

**Comment by kolanos** [comment]
@svarughese91 Can you provide your `serverless.yml`? (be sure to omit any secrets)

The `newrelic-lambda-wrapper` module is provided by the layer, but `'./newrelic-lambda-wrapper.js'` is a relative import and doesn't look right.

**Comment by svarughese91** [comment]
Sure yes here is the serverless.yml

```
name: Dev Deploy

on:
  push:
    branches: [ dev ]

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.XXXXXXXX}}
  AUTH0CLIENTID: ${{ secrets.XXXXXXXX }}
  AUTH0CLIENTSECRET: ${{ secrets.XXXXXXXX }}
  AUTH0_IDENTIFIER: https://XXXXXXXX.com
  NODE_ENV: dev
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Send Slack message at start of deploy
    - uses: rtCamp/action-slack-notify@v2.0.0
      name: Slack Notification
      env:
        SLACK_CHANNEL: build-automation
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: XXXXXXXX
        SLACK_MESSAGE: 'Starting test'
        SLACK_TITLE: Dev Test Deploy
        SLACK_USERNAME: Tesr-CICD
        SLACK_WEBHOOK: ${{ secrets.XXXXXXXX }}
      # Check out from repo and setup node environment
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run test
      #On failure send slack message
    - uses: rtCamp/action-slack-notify@v2.0.0
      if: failure()
      name: Slack Notification
      env:
        SLACK_CHANNEL: build-automation
        SLACK_COLOR: '#FC100D'
        SLACK_ICON:XXXXXXXX
        SLACK_MESSAGE: ':rotating_light: Dev Test Deployment Failure'
        SLACK_TITLE: Dev Test Deploy Failure
        SLACK_USERNAME: XXXXXXXX
        SLACK_WEBHOOK: ${{ secrets.XXXXXXXX }}
      
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g serverless
    - run: npm install
    - name: Deploy Dev
      run: npm run deploy:dev
      #On succces send slack message
    - uses: rtCamp/action-slack-notify@v2.0.0
      if: success()
      name: Slack Notification
      env:
        SLACK_CHANNEL: build-automation
        SLACK_COLOR: '#28a745'
        SLACK_ICON: XXXXXXXX
        SLACK_MESSAGE: 'Dev Test Deployed :rocket:'
        SLACK_TITLE: Dev Test Deploy Complete
        SLACK_USERNAME: XXXXXXXX
        SLACK_WEBHOOK: ${{ secrets.XXXXXXXX }}
      #On failure send slack message
    - uses: rtCamp/action-slack-notify@v2.0.0
      if: failure()
      name: Slack Notification
      env:
        SLACK_CHANNEL: build-automation
        SLACK_COLOR: '#FC100D'
        SLACK_ICON: XXXXXXXX
        SLACK_MESSAGE: ':rotating_light: Dev Test Deployment Failure'
        SLACK_TITLE: Dev Test Deploy Failure
        SLACK_USERNAME: XXXXXXXX
        SLACK_WEBHOOK: ${{ secrets.XXXXXXXX }}
```

**Comment by mrickard** [comment]
@svarughese91 That should be enough to get you deploying...though I am wondering about that `newrelic-lambda-wrapper.js`--are you referencing that as an import or require in your function code?

**Comment by svarughese91** [comment]
nope its not being referenced in the code, if i remove:   - serverless-newrelic-lambda-layers from the serverless yaml it deploys fine, which indicates it could be something with the plugin?

**Comment by mrickard** [comment]
@svarughese91 Thank you!  Just out of curiosity, if you deploy a test function into a different region, does it deploy correctly, or is it the same error?

**Comment by mrickard** [comment]
@svarughese91 I've done a successful deployment/invocation of a clean test function in us-east-1, with this minimal package.json and serverless.yml: 

package.json:
```
{
  "devDependencies": {
    "serverless-newrelic-lambda-layers": "^0.2.3"
  }
}
```

serverless.yml:
```
service: deploymenttest

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 6
  region: us-east-1
  logRetentionInDays: 1

functions:
  deployTest:
    handler: handler.deployTest

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: {$env:myAccountId}
```

Would you be able to share your package.json?
